--Syntax of creating a table n sql developer

CREATE TABLE TABLE_NMAE(COLUMN_NAME DATATYPE,COLUMN_NAME DATATYPE)

--EXAMPLE:
CREATE TABLE EMPLOYEE12(EMP_ID INT,EMP_NMAE VARCHAR(10),EMP_ADDRESS VARCHAR(12));

--INSERTING A VALUE IN TABLE
INSERT INTO EMPLOYEE12(EMP_ID,EMP_NAME,EMP_ADDRESS)VALUES(1,'ROY','PUNE'); 
INSERT INTO EMPLOYEE12(EMP_ID,EMP_NAME,EMP_ADDRESS)VALUES(2,'ALLICE','BANGLORE');
--OR
INSERT INTO EMPLOYEE12 VALUES(3,'REHAN','LONAWALA');


SELECT * FROM EMPLOYEE12;

